# Generated by Django 5.1.2 on 2024-11-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_alter_userprofile_last_data_update_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spotifywraphistory",
            name="included_genres",
        ),
        migrations.RemoveField(
            model_name="spotifywraphistory",
            name="listening_minutes",
        ),
        migrations.RemoveField(
            model_name="spotifywraphistory",
            name="time_range",
        ),
        migrations.RemoveField(
            model_name="spotifywraphistory",
            name="unique_artists_count",
        ),
        migrations.RemoveField(
            model_name="spotifywraphistory",
            name="unique_tracks_count",
        ),
        migrations.RemoveField(
            model_name="spotifywraphistory",
            name="wrap_data",
        ),
        migrations.AddField(
            model_name="spotifywraphistory",
            name="top_album",
            field=models.JSONField(default=dict, help_text="Single top album"),
        ),
        migrations.AddField(
            model_name="spotifywraphistory",
            name="top_albums",
            field=models.JSONField(default=dict, help_text="List of top albums"),
        ),
        migrations.AddField(
            model_name="spotifywraphistory",
            name="top_artist",
            field=models.JSONField(default=dict, help_text="Single top artist"),
        ),
        migrations.AddField(
            model_name="spotifywraphistory",
            name="top_artists",
            field=models.JSONField(default=dict, help_text="List of top artists"),
        ),
        migrations.AddField(
            model_name="spotifywraphistory",
            name="top_followed_artists",
            field=models.JSONField(default=dict, help_text="Top 5 followed artists"),
        ),
        migrations.AddField(
            model_name="spotifywraphistory",
            name="top_genres",
            field=models.JSONField(default=list, help_text="List of top genres"),
        ),
        migrations.AddField(
            model_name="spotifywraphistory",
            name="top_track",
            field=models.JSONField(default=dict, help_text="Single top track/song"),
        ),
        migrations.AddField(
            model_name="spotifywraphistory",
            name="top_tracks",
            field=models.JSONField(default=dict, help_text="List of top tracks/songs"),
        ),
    ]
