# Generated by Django 5.1.2 on 2024-11-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_remove_spotifywraphistory_included_genres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifywraphistory",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
