# Generated by Django 5.1.2 on 2024-11-24 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_spotifywraphistory_is_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="WrapLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.userprofile",
                    ),
                ),
                (
                    "wrap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="mainapp.spotifywraphistory",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_profile", "wrap")},
            },
        ),
    ]
